### ISSUE TITLE
Docker could not find /codes/ MVS_codes /....

### ISSUE THREAD

**Issue by qianshipoi** [chaytonmin/DeepMVS#5]
## Is the content in Docker not updated?
![QQ截图20220727171330](https://user-images.githubusercontent.com/43244500/181211221-b87c2c90-d2e2-4b11-b6a2-c216a0bef8f7.jpg)
![QQ截图20220727171320](https://user-images.githubusercontent.com/43244500/181211214-50477526-697e-4f79-b662-a888ac999085.jpg)

**Comment by chaytonmin** [comment]
> ## Is the content in Docker not updated?
> ![QQ截图20220727171330](https://user-images.githubusercontent.com/43244500/181211221-b87c2c90-d2e2-4b11-b6a2-c216a0bef8f7.jpg) ![QQ截图20220727171320](https://user-images.githubusercontent.com/43244500/181211214-50477526-697e-4f79-b662-a888ac999085.jpg)

You need to link the file path to the docker when start the docker
